
default_platform :android

platform :android do
  ENV["FASTLANE_HIDE_CHANGELOG"] = "true"
  ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "true"
  PROJECT_NAME = "coderproprementprojet"

# public lanes
  desc "build"
  lane :build_debug do |options|
    gradle(
      task: "clean",
    )
    gradle(
      task: "assembleDebug",
    )
    sh "build-apk.sh"
  end

  desc "unit tests"
  lane :unit_test do |options|
    gradle(
      task: "clean",
    )
    gradle(
      task: "testDebugUnitTest",
    )
  end
end
